#################################################################
##   LGA estimates of community MMR                            ##
##   functions.R                                               ##
##   Purpose:  Assorted functions for plotting, model etc.     ##
##   Author: Anu Mishra                                        ##  
##   Created 6/9/25                                            ##
#################################################################

### Quick summary matrix
summarize_draws <- function(samples_matrix, param_name) {
  colnames(samples_matrix) <- paste0(param_name, "_", seq_len(ncol(samples_matrix)))
  
  as.data.frame(samples_matrix) %>%
    pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>%
    mutate(LGA = as.integer(gsub(".*_", "", param))) %>%
    group_by(LGA) %>%
    summarise(
      mean   = mean(value),
      median = median(value),
      lower_95 = quantile(value, 0.025),
      upper_95 = quantile(value, 0.975),
      .groups = "drop"
    ) %>%
    rename_with(~paste0(param_name, "_", .), -LGA)
}


### Posterior plots --- Code generated by chatGPT
plot_prior_vs_posterior <- function(samples,param_name, prior_defs) {
  # Extract posterior samples
  post <-  unlist(lapply(samples, function(chain) chain[, param_name]))
  
  # Lookup prior info
  prior <- prior_defs[[param_name]]
  prior_type <- prior$type
  mean <- prior$mean
  sd <- prior$sd
  
  # x range for prior
  x_range <- switch(prior_type,
                          "norm" = seq(-50,50,length.out = 1000),
                          "half-normal" = seq(0,50,length.out = 1000),
                          stop("Unsupported prior type")
  )
  
  
  # Compute prior density
  prior_density <- switch(prior_type,
                          "norm" = dnorm(x_range, mean = mean, sd = sd),
                          "half-normal" = dnorm(x_range, mean = mean, sd = sd) * 2,
                          stop("Unsupported prior type")
  )
  
  # Prepare data for ggplot
  df_prior <- data.frame(x = x_range, y = prior_density,method = "Prior")
  df_post <- data.frame(x = post,method = "Posterior")
  
  ggplot() +
    geom_line(data = df_prior, aes(x = x, y = y, color = method), linetype = "dashed", size = 1.2) +
    geom_density(data = df_post, aes(x = x, fill = method), alpha = 0.4, color = NA) +
    scale_color_manual(values = c("Prior" = "gray30", "Posterior" = "skyblue4")) +
    scale_fill_manual(values = c("Posterior" = "skyblue")) +
    labs(title = paste("Prior vs Posterior:", param_name),
         x = "Value", y = "Density", fill = "", color = "") +
    theme_minimal() +
    coord_cartesian(xlim=c(min(post)-5,max(post)+5)) +
    theme(legend.position = "top")
  }


